import random
import datetime

# Minified CSS and Header
header = """---
dg-publish: true
title: 微博客 (Stress Test)
created: 2024-01-10
---
<style>
:root{--bg-color:#f5f7fa;--card-bg:#ffffff;--text-primary:#333333;--text-secondary:#666666;--accent-color:#007bff;--border-radius:12px;--box-shadow:0 2px 8px rgba(0,0,0,0.05)}@media(prefers-color-scheme:dark){:root{--bg-color:transparent;--card-bg:#2d2d2d;--text-primary:#e0e0e0;--text-secondary:#aaaaaa;--box-shadow:0 2px 8px rgba(0,0,0,0.2)}}.markdown-preview-view{padding:0!important}.timeline{max-width:600px;width:100%;margin:0 auto;display:flex;flex-direction:column;gap:20px;padding-top:20px}.header{text-align:center;margin-bottom:20px}.header h1{margin:0;font-size:1.5rem;border-bottom:none!important}.header p{color:var(--text-secondary);font-size:0.9rem}.memo-card{background-color:var(--card-bg);border-radius:var(--border-radius);padding:16px;box-shadow:var(--box-shadow);display:flex;gap:12px;transition:transform .2s;border:1px solid rgba(128,128,128,0.1)}.memo-card:hover{transform:translateY(-2px)}.avatar{width:40px;height:40px;border-radius:50%;background-color:#ddd;flex-shrink:0;overflow:hidden}.avatar img{width:100%;height:100%;object-fit:cover;margin:0!important;display:block}.content-area{flex:1}.meta{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}.author{font-weight:600;font-size:.95rem}.time{color:var(--text-secondary);font-size:.8rem}.text{line-height:1.6;margin-bottom:12px;white-space:pre-wrap}.text a{color:var(--accent-color);text-decoration:none}.text .tag{color:var(--accent-color);background-color:rgba(0,123,255,0.1);padding:2px 6px;border-radius:4px;font-size:.85rem}.images-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(100px,1fr));gap:8px;margin-top:12px}.image-item{aspect-ratio:1;border-radius:8px;overflow:hidden;background-color:#eee;cursor:pointer}.image-item img{width:100%;height:100%;object-fit:cover;margin:0!important;transition:transform .3s;display:block}.image-item:hover img{transform:scale(1.05)}
</style><!-- No newlines between HTML tags to prevent auto-formatting --><div class="timeline"><div class="header"><h1>我的微博客 (100条测试)</h1><p>Stress Test Generated by Python</p></div>"""

# Template for memo card - ensuring no newlines around critical tags
card_template = """<div class="memo-card"><div class="avatar"><img src="https://ui-avatars.com/api/?name=User&background=0D8ABC&color=fff" alt="Avatar"></div><div class="content-area"><div class="meta"><span class="author">Me</span><span class="time">{time}</span></div><div class="text">{content}</div>{images}</div></div>"""

texts = [
    "今天天气真不错，适合写代码！#coding #life",
    "Thinking about the future of PKM tools. Local-first is the way.",
    "Just fixed a bug in the production environment. Phew! 😅",
    "Is Flutter the future of cross-platform dev? I think so.",
    "Reading a great book on system design.",
    "Coffee time! ☕",
    "Obsidian + Digital Garden + MD Bro = Perfect Workflow.",
    "Does anyone know how to optimize 11ty build speeds?",
    "Reviewing some PRs today. Code quality is improving.",
    "Started a new project. Excited!"
]

html_parts = []
base_time = datetime.datetime.now()

for i in range(100):
   time_str = (base_time - datetime.timedelta(hours=i*2)).strftime("%Y-%m-%d %H:%M")
   text = random.choice(texts) + f" (Item {i+1})"
   
   has_image = random.random() > 0.7
   images_html = ""
   if has_image:
       count = random.randint(1, 4)
       imgs = ""
       for j in range(count):
           # Added loading="lazy" for performance
           imgs += f'<div class="image-item"><img src="https://picsum.photos/200/200?random={i*10+j}" alt="Image" loading="lazy"></div>'
       images_html = f'<div class="images-grid">{imgs}</div>'
   
   card = card_template.format(time=time_str, content=text, images=images_html)
   html_parts.append(card)

footer = "</div>"

full_content = header + "".join(html_parts) + footer

with open("microblog_demo_long.md", "w", encoding="utf-8") as f:
    f.write(full_content)

print("Generated microblog_demo_long.md with 100 items.")
